stages:
  - check
  - test
  - build
  - test release
  - release

before_script:
  - export LANG=en_US.UTF-8

# check:
#   stage: check
#   image: quay.io/prodsecdev/fedora-latest:latest  # includes tox
#   script:
#     - dnf install -y python3.9
#     - tox

# test:
#   stage: test
#   image: quay.io/prodsecdev/fedora-latest:latest  # includes all deps
#   script:
#     - dnf install -y python3.9
#     - tox -e unit-tests

test-build:
  stage: build
  image: quay.io/prodsecdev/fedora-latest:latest
  script:
    - dnf install -y python3.9 python3-pip
    - python3 -m venv venv && source venv/bin/activate
    - python3 -m pip install --upgrade build
    - python3 -m build
  except:
    - tags

build:
  stage: build
  image: quay.io/prodsecdev/fedora-latest:latest
  script:
    - dnf install -y python3.9 python3-pip
    - python3 -m venv venv && source venv/bin/activate
    - python3 -m pip install --upgrade build
    - python3 -m build
  artifacts:
    untracked: false
    expire_in: 1 week
    paths:
     - dist/
  only:
    - /\d+\.\d+\.\d+/
  except:
    - branches

test-pypi-release:
  stage: test release
  image: quay.io/prodsecdev/fedora-latest:latest
  dependencies:
    - build
  script:
    - dnf install -y python3.9 python3-pip
    - python3 -m venv venv && source venv/bin/activate
    - python3 -m pip install --upgrade twine
    - python3 -m twine upload --repository testpypi dist/* -u __token__ -p $TEST_PYPI_TOKEN
  only:
    - /\d+\.\d+\.\d+/
  except:
    - branches

# test
# pypi-release:
#   stage: release
#   image: quay.io/prodsecdev/fedora-latest:latest
#   dependencies:
#     - build
#   script:
#     - dnf install -y python3.9 python3-pip
#     - python3 -m venv venv && source venv/bin/activate
#     - python3 -m pip install --upgrade twine
#     - python3 -m twine upload --repository testpypi dist/* -u __token__ -p $TEST_PYPI_TOKEN
#   only:
#     - master
#     - tags
